//la liste des layer à changer les visibility
ChangeLayerVisibilityGreen[0]="floorGreen"
ChangeLayerVisibilityGreen[1]="below_playerGreen"
ChangeLayerVisibilityGreen[2]="over_playerGreen"


ChangeLayerVisibilityWhite[0]="floorWhite"
ChangeLayerVisibilityWhite[1]="below_playerWhite"
ChangeLayerVisibilityWhite[2]="over_playerWhite"

ChangeLayerVisibilityRed[0]="floorRed"
ChangeLayerVisibilityRed[1]="below_playerRed"
ChangeLayerVisibilityRed[2]="over_playerRed"

ChangeLayerVisibilityPurple[0]="floorPurple"
ChangeLayerVisibilityPurple[1]="below_playerPurple"
ChangeLayerVisibilityPurple[2]="over_playerPurple"


t_scene_info=[
	[cutscene_change_variable,FadeInFadeOut,"spawnRoom", rm_roadGurovinuAkayaVillage2],
	[cutscene_change_variable,FadeInFadeOut,"spawnX", 713],
	[cutscene_change_variable,FadeInFadeOut,"spawnY", 1014],
	[cutscene_layer_visibility, ChangeLayerVisibilityWhite],
	[cutscene_layer_visibility, ChangeLayerVisibilityGreen],
	[cutscene_layer_visibility, ChangeLayerVisibilityPurple],
	[cutscene_wait, 1],
	[cutscene_play_sound,Snd_TheOpening,1,false],
	[cutscene_wait, 5],
	[cutscene_instances_create,x,y,"HUD",Obj_OpTitle],
	[cutscene_alpha_up,Obj_OpTitle],
	[cutscene_wait, 7.4],
	[cutscene_change_variable,Obj_OpTitle,"scale",2.3],
	[cutscene_wait, 1/6],
	[cutscene_change_variable,Obj_OpTitle,"scale",2.6],
	[cutscene_wait, 1/6],
	[cutscene_change_variable,Obj_OpTitle,"scale",3],
	[cutscene_wait, 1/6],
	[cutscene_instances_destroy,Obj_OpTitle],
	[cutscene_wait, 1/3],
	[cutscene_layer_visibility, ChangeLayerVisibilityGreen],
	[cutscene_layer_visibility, ChangeLayerVisibilityRed],
	[cutscene_create_credit,POSITIONS.DownLeft,"Initial Idea","Adam Boukhari"],
	[cutscene_wait, 9.25],
	[cutscene_layer_visibility, ChangeLayerVisibilityWhite],
	[cutscene_instances_destroy, Obj_OpeningCredits],
	[cutscene_layer_visibility, ChangeLayerVisibilityGreen],
	[cutscene_create_credit,POSITIONS.DownRight,"Original Story from","Adam Boukhari"],	
	[cutscene_wait, 9.25],
	[cutscene_instances_destroy, Obj_OpeningCredits],
	[cutscene_set_lighting,c_orange],
	[cutscene_create_credit,POSITIONS.TopLeft,"Main Programmer","Adam Boukhari"],	
	[cutscene_wait, 2],
	[cutscene_set_lighting,c_navy],
	[cutscene_create_credit,POSITIONS.TopRight,"Movement Programmer","Benjamen Caron"],	
	[cutscene_wait, 2.25],
	[cutscene_instances_destroy,Obj_DayLighting],
	[cutscene_wait, 2],
	[cutscene_layer_visibility, ChangeLayerVisibilityGreen],
	[cutscene_instances_destroy, Obj_OpeningCredits],
	[cutscene_layer_visibility, ChangeLayerVisibilityWhite],
	[cutscene_wait, 2.8],
	[cutscene_set_lighting,c_orange],
	[cutscene_create_credit,POSITIONS.DownRight,"Main Artist","Adam Boukhari"],
	[cutscene_wait, 2],
	[cutscene_set_lighting,c_navy],
	[cutscene_create_credit,POSITIONS.DownLeft,"Pixel-Artist","Adam Boukhari"],
	[cutscene_wait, 2],
	[cutscene_instances_destroy, Obj_OpeningCredits],
	[cutscene_layer_visibility, ChangeLayerVisibilityGreen],
	
	[cutscene_instances_destroy,Obj_DayLighting],
	[cutscene_wait, 4],
	[cutscene_set_lighting,c_white],
	[cutscene_layer_visibility, ChangeLayerVisibilityGreen],
	[cutscene_wait, 0.15],
	[cutscene_create_credit,POSITIONS.DownLeft,"Sprite Animator","Adam Boukhari"],
	[cutscene_instances_destroy,Obj_DayLighting],
	[cutscene_wait, 2.25],
	[cutscene_set_lighting,c_navy],
	[cutscene_create_credit,POSITIONS.DownRight,"Cinematics Animator","Adam Boukhari"],
	[cutscene_wait, 2.25],
	[cutscene_instances_destroy,Obj_DayLighting],
	[cutscene_instances_destroy, Obj_OpeningCredits],
	[cutscene_layer_visibility, ChangeLayerVisibilityPurple],
	[cutscene_layer_visibility, ChangeLayerVisibilityGreen],
	[cutscene_instances_create,x,y,"Player",Obj_OpSensei1],
	[cutscene_create_credit,POSITIONS.DownLeft,"Musics","Remixers on youtube"],
	[cutscene_wait, 2],
	[cutscene_instances_destroy, Obj_OpeningCredits],
	[cutscene_layer_visibility, ChangeLayerVisibilityRed],
	[cutscene_instances_destroy,Obj_OpSensei1],
	[cutscene_create_credit,POSITIONS.TopRight,"Musics","Nintendo"],
	[cutscene_layer_visibility, ChangeLayerVisibilityPurple],
	[cutscene_instances_create,x,y,"Player",Obj_OpSensei2],
	[cutscene_wait, 2.5],
	[cutscene_instances_destroy, Obj_OpeningCredits],
	[cutscene_layer_visibility, ChangeLayerVisibilityRed],
	[cutscene_instances_destroy,Obj_OpSensei2],
	[cutscene_wait, 0.1],
	[cutscene_set_lighting,c_white],
	[cutscene_layer_visibility, ChangeLayerVisibilityWhite],
	[cutscene_wait, 0.1],
	[cutscene_create_credit,POSITIONS.DownLeft,"Musics","Square Enix/Disney"],
	[cutscene_create_credit,POSITIONS.TopRight,"Musics","Atlus"],
	[cutscene_instances_destroy,Obj_DayLighting],
	[cutscene_wait, 2],
	[cutscene_instances_destroy, Obj_OpeningCredits],
	[cutscene_layer_visibility, ChangeLayerVisibilityWhite],
	[cutscene_wait, 0.1],
	[cutscene_set_lighting,c_white],
	[cutscene_layer_visibility, ChangeLayerVisibilityPurple],
	[cutscene_wait, 0.1],
	[cutscene_instances_destroy,Obj_DayLighting],
	[cutscene_create_credit,POSITIONS.DownRight,"Musics","Toei Animation"],
	[cutscene_create_credit,POSITIONS.TopLeft,"Musics","Toby Fox"],
	[cutscene_wait, 7],
	[cutscene_instances_destroy, Obj_OpeningCredits],
	[cutscene_layer_visibility, ChangeLayerVisibilityRed],
	[cutscene_layer_visibility, ChangeLayerVisibilityPurple],
	[cutscene_wait, 0.25],
	[cutscene_layer_visibility, ChangeLayerVisibilityWhite],
	[cutscene_layer_visibility, ChangeLayerVisibilityRed],
	[cutscene_wait, 0.25],
	
	[cutscene_create_credit,POSITIONS.TopRight,"Not a game from","Hideo Kojima"],
	[cutscene_layer_visibility, ChangeLayerVisibilityGreen],
	[cutscene_layer_visibility, ChangeLayerVisibilityWhite],
	[cutscene_wait, 7],
	[cutscene_instances_destroy, Obj_OpeningCredits],
	[cutscene_wait, 5.5],
	[cutscene_change_variable,FadeInFadeOut,"doTransition", true],
	[cutscene_change_sprite,Obj_Purakushisu,Spr_PurakushisuIddleUp],
	[cutscene_change_variable,Obj_Purakushisu, "pause", false],
]